version: '3.8'

services:
  bot:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    # Раскомментируйте, если нужно монтировать .env как volume
    # volumes:
    #   - ./.env:/root/.env