name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 89.110.83.57 >> ~/.ssh/known_hosts

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build the project
      run: |
        GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o myapp main.go

    - name: Prepare server directory
      run: |
        ssh -o StrictHostKeyChecking=no root@89.110.83.57 "mkdir -p /var/www/myapp && rm -rf /var/www/myapp/*"

    - name: Deploy to server
      run: |
        scp -r ./* root@89.110.83.57:/var/www/myapp/

    - name: Restart bot on server
      run: |
        ssh -o StrictHostKeyChecking=no root@89.110.83.57 << 'EOF'
        pkill -f myapp || true
        nohup /var/www/myapp/myapp > /var/www/myapp/myapp.log 2>&1 &
        EOF

    - name: Notify success
      if: success()
      run: echo "Deploy successful!"

    - name: Notify failure
      if: failure()
      run: echo "Deploy failed!"
