name: Deploy to Server

on:
  push:
    branches:
      - main  # Запускать Workflow при пуше в ветку main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Проверяем код из репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Устанавливаем SSH-ключ
      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.KARMA_SECRET }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # 3. Настраиваем доступ к серверу
      - name: Add server to known_hosts
        run: ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      # 4. Компилируем приложение
      - name: Build Go application
        run: |
          GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o myapp main.go

      # 5. Загружаем приложение на сервер
      - name: Deploy to server
        run: |
          scp -o StrictHostKeyChecking=no myapp root@${{ secrets.SERVER_HOST }}:/var/www/myapp/

      # 6. Выполняем команды на сервере
      - name: Restart application
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.SERVER_HOST }} << 'EOF'
          pkill -f myapp || true
          nohup /var/www/myapp/myapp > /var/www/myapp/myapp.log 2>&1 &
          EOF
