name: Deploy Telegram Bot with Docker

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 89.110.83.57 >> ~/.ssh/known_hosts

    - name: Build Docker image
      run: |
        docker build -t mytelegrambot:latest .

    - name: Save Docker image as tarball
      run: |
        docker save mytelegrambot:latest > mytelegrambot.tar

    - name: Copy Docker image to server
      run: |
        scp mytelegrambot.tar root@89.110.83.57:/var/www/mytelegrambot/

    - name: Load and run Docker image on server
      run: |
        ssh -o StrictHostKeyChecking=no root@89.110.83.57 << 'EOF'
        docker load < /var/www/mytelegrambot/mytelegrambot.tar
        docker stop mytelegrambot || true
        docker rm mytelegrambot || true
        docker run -d --name mytelegrambot mytelegrambot:latest
        EOF
